Table movies {
  id integer [primary key]
  title varchar
  release_year integer 
}

Table finance {
  movie_id integer [primary key]
  budget float
  box_office float
}

Ref: finance.movie_id - movies.id
